# Generated by Django 4.2.7 on 2023-11-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_voo', models.CharField(max_length=100)),
                ('data_voo', models.IntegerField()),
                ('hora_voo', models.TimeField()),
            ],
        ),
    ]
